seed: 2022
device: cuda
run_folder: runs
has_ckp: False
cover_path: ''
stego_path: ''
valid_cover_path: ''
valid_stego_path: ''
batch_size: 32
start_epoch: 1
num_epochs: 500
print_freq: 10
resize: 256
train_size: 2400
val_size: 1000
test_size: 1000
p_rot: 0.1
p_hflip: 0.1
lr: 1e-3
ckp: ''